routes:
  /:
    template: home
  /sw.js/:
    template: sw
    content_type: application/javascript
  /manifest.json/:
    template: manifest
    content_type: application/json
  /offline/:
    template: offline

collections:
  /videos/:
    permalink: /videos/{slug}/
    filter: tag:hash-video
    template: videos
  /projects/:
    permalink: /projects/{slug}/
    filter: tag:hash-project
    template: projects
  /courses/:
    permalink: /courses/{slug}/
    filter: tag:hash-course
    template: courses
  /lessons/:
    permalink: /lessons/{slug}/
    filter: tag:hash-lesson
    template: lessons
  /webseries/:
    permalink: /webseries/{slug}/
    filter: tag:hash-webseries
    template: webseries
  /episodes/:
    permalink: /episodes/{slug}/
    filter: tag:hash-episode
    template: episodes
  /products/:
    permalink: /products/{slug}/
    filter: tag:hash-product
    template: products
  /timeline/:
    permalink: /timeline/{slug}/
    filter: tag:hash-timeline
    template: timeline
  /changelog/:
    permalink: /changelog/{slug}/
    filter: tag:hash-changelog
    template: changelog
  /newsletters/:
    permalink: /newsletters/{slug}/
    filter: tag:hash-newsletter
    template: newsletters
  /blog/:
    permalink: /blog/{slug}/
    template: blog

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
