#!/usr/bin/env node
/**
 * Regenerates INVENTORY.md from the Creator Design System source.
 *
 *   node .claude/skills/design-system/sync.mjs            # always regenerate
 *   node .claude/skills/design-system/sync.mjs --if-stale # only if the DS changed
 *
 * Staleness = DS git HEAD or newest source mtime differs from what the last
 * inventory recorded. Cheap enough to run at the top of every skill invocation.
 */

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const THEME = path.resolve(HERE, '../../..');
const OUT = path.join(HERE, 'INVENTORY.md');

function resolveDs() {
	const linked = path.join(THEME, 'node_modules', 'creator-design-system');
	if (fs.existsSync(path.join(linked, 'src', 'index.css'))) return fs.realpathSync(linked);

	const pkg = JSON.parse(fs.readFileSync(path.join(THEME, 'package.json'), 'utf8'));
	const spec = pkg.dependencies?.['creator-design-system'] ?? '';
	if (spec.startsWith('file:')) {
		const p = path.resolve(THEME, spec.slice('file:'.length));
		if (fs.existsSync(path.join(p, 'src', 'index.css'))) return p;
	}
	return null;
}

const DS = resolveDs();
if (!DS) {
	console.error(
		'design-system sync: cannot find creator-design-system.\n' +
			'Expected node_modules/creator-design-system or a file: dependency in package.json.\n' +
			'Fix: npm install (the dep is file:../../../../Projects/Creator-Design-System).'
	);
	process.exit(1);
}

const head = (() => {
	try {
		return execFileSync('git', ['-C', DS, 'rev-parse', '--short', 'HEAD'], {
			encoding: 'utf8',
			stdio: ['ignore', 'pipe', 'ignore'],
		}).trim();
	} catch {
		return 'no-git';
	}
})();

const dirty = (() => {
	try {
		return execFileSync('git', ['-C', DS, 'status', '--porcelain'], {
			encoding: 'utf8',
			stdio: ['ignore', 'pipe', 'ignore'],
		}).trim().length > 0;
	} catch {
		return false;
	}
})();

function walk(dir, filter, acc = []) {
	if (!fs.existsSync(dir)) return acc;
	for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
		const full = path.join(dir, entry.name);
		if (entry.isDirectory()) walk(full, filter, acc);
		else if (filter(entry.name)) acc.push(full);
	}
	return acc;
}

const sources = walk(path.join(DS, 'src'), (n) => n.endsWith('.css') || n.endsWith('.js'));
const newestMtime = sources.reduce((max, f) => Math.max(max, fs.statSync(f).mtimeMs), 0);
const stamp = `${head}${dirty ? '+dirty' : ''}:${Math.round(newestMtime)}`;

if (process.argv.includes('--if-stale') && fs.existsSync(OUT)) {
	const prev = fs.readFileSync(OUT, 'utf8').match(/<!-- stamp: (.+?) -->/)?.[1];
	if (prev === stamp) {
		console.log(`design-system sync: up to date (${stamp})`);
		process.exit(0);
	}
}

// ---- extraction ------------------------------------------------------------

const CLASS_RE = /(?:^|[\s,>+~(])(\.[a-zA-Z][\w-]*)/g;
const VAR_DEF_RE = /^\s*(--[a-zA-Z][\w-]*)\s*:/gm;

function extract(file) {
	const css = fs.readFileSync(file, 'utf8').replace(/\/\*[\s\S]*?\*\//g, '');
	const classes = new Set();
	const vars = new Set();
	// selectors only: text before each `{`
	for (const block of css.split('{')) {
		const sel = block.slice(block.lastIndexOf('}') + 1);
		for (const m of sel.matchAll(CLASS_RE)) classes.add(m[1]);
	}
	for (const m of css.matchAll(VAR_DEF_RE)) vars.add(m[1]);
	return { classes: [...classes].sort(), vars: [...vars].sort() };
}

const LAYERS = fs
	.readdirSync(path.join(DS, 'src'), { withFileTypes: true })
	.filter((e) => e.isDirectory())
	.map((e) => e.name)
	.sort();

const dsPkg = JSON.parse(fs.readFileSync(path.join(DS, 'package.json'), 'utf8'));

let md = '';
md += `<!-- stamp: ${stamp} -->\n`;
md += `<!-- GENERATED by .claude/skills/design-system/sync.mjs — do not edit by hand. -->\n\n`;
md += `# Creator Design System — inventory\n\n`;
md += `- Source: \`${DS}\`\n`;
md += `- Version: \`${dsPkg.version}\` · commit \`${head}\`${dirty ? ' (uncommitted changes present)' : ''}\n`;
md += `- Entry points: ${Object.keys(dsPkg.exports ?? {})
	.map((k) => `\`${k}\``)
	.join(', ')}\n\n`;
md += `Every class and token below is defined in the DS source. If something you need\n`;
md += `is not listed, it does not exist yet — add it to the DS, don't reinvent it in the theme.\n\n`;

for (const layer of LAYERS) {
	const files = walk(path.join(DS, 'src', layer), (n) => n.endsWith('.css')).filter(
		(f) => path.basename(f) !== 'index.css'
	);
	if (!files.length) continue;
	md += `## ${layer}\n\n`;
	for (const file of files) {
		const { classes, vars } = extract(file);
		if (!classes.length && !vars.length) continue;
		md += `### \`src/${layer}/${path.basename(file)}\`\n\n`;
		if (vars.length) md += `**Tokens** (${vars.length}): ${vars.map((v) => `\`${v}\``).join(', ')}\n\n`;
		if (classes.length) md += `**Classes** (${classes.length}): ${classes.map((c) => `\`${c}\``).join(', ')}\n\n`;
	}
}

const js = walk(path.join(DS, 'src'), (n) => n.endsWith('.js'));
if (js.length) {
	md += `## Scripts\n\n`;
	for (const f of js) {
		const first = fs
			.readFileSync(f, 'utf8')
			.split('\n')
			.slice(0, 12)
			.map((l) => l.replace(/^\s*(\/\*+|\*+\/?|\/\/)\s?/, '').trim())
			.filter(Boolean)[0] ?? '';
		md += `- \`src/${path.relative(path.join(DS, 'src'), f)}\` — ${first}\n`;
	}
	md += '\n';
}

const docs = fs.existsSync(path.join(DS, 'docs'))
	? fs
			.readdirSync(path.join(DS, 'docs'))
			.filter((n) => n.endsWith('.html'))
			.sort()
	: [];
if (docs.length) {
	md += `## Doc pages (\`docs/\`, live at https://creator.imswarnil.com)\n\n`;
	md += docs.map((d) => `\`${d.replace(/\.html$/, '')}\``).join(', ') + '\n\n';
	md += `Read the matching \`docs/<name>.html\` for real markup examples of any component.\n`;
}

fs.writeFileSync(OUT, md);
console.log(`design-system sync: wrote INVENTORY.md (${stamp}, ${sources.length} source files)`);
